name: CI on Self-Hosted
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: glpi-server
    steps:
      - uses: actions/checkout@v4
      - name: Run a script
        run: echo "Running on my self-hosted runner!"
